# Site settings
title: ML@SITraN
email: 
description: > # this means to ignore newlines until "baseurl:"
  The portion of the Sheffield machine learning group located at SITraN.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: lawrennd
github_username:  SheffieldML

# Build settings
markdown: kramdown
